---
- name: Gather ec2 facts
  action: ec2_facts

- name: Python Package manager
  apt: pkg=python-pip state=present

- name: Install boto
  pip: name=boto

- name: Use the Name tag as hostname if given
  set_fact:
    aws_hostname: "{{ aws_tags.Name | default(ansible_fqdn) }}"

- include: tags.yml
- include: snapshots.yml
- include: alarms.yml
