---
- name: Gather ec2 facts
  action: ec2_facts

- name: Python Package manager
  apt: pkg=python-pip state=present

- name: Install boto
  pip: name=boto

- include: tags.yml
- include: snapshots.yml
- include: alarms.yml
