---
- name: Tag the instance
  ec2_tag:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: present
    tags: "{{ aws_tags }}"

- name: List the volumes of this instance
  ec2_vol:
    instance: "{{ ansible_ec2_instance_id }}"
    region: "{{ ansible_ec2_placement_region }}"
    state: list
  register: ec2_vol

- name: Tag the volumes of this instance
  ec2_tag:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ item.id }}"
    state: present
    tags: "{{ aws_tags }}"
  with_items: "{{ ec2_vol.volumes }}"

- name: Get ENI facts
  ec2_eni_facts:
    region: "{{ ansible_ec2_placement_region }}"
    filters:
      attachment.instance-id: "{{ ansible_ec2_instance_id }}"
  register: ec2_eni

- name: Tag the interface of this instance
  ec2_tag:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ item.id }}"
    state: present
    tags: "{{ aws_tags }}"
  with_items: "{{ ec2_eni.interfaces }}"
